# Generated by Django 3.1.7 on 2021-03-29 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_from', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_to', models.CharField(blank=True, max_length=50, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptiontypecode', models.CharField(blank=True, max_length=50, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('service_code', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('Subsriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subsriber')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=50, null=True)),
                ('attribution', models.CharField(blank=True, max_length=50, null=True)),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.officer')),
            ],
        ),
    ]
